version: "3.8"
services:
  ingest:
    image: devseed-labs/eoapi-risk-ingest:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/app/
  # db:
  #   image: osmseed-osmcha-db:v1
  #   build:
  #     context: ../images/osmcha-db
  #     dockerfile: Dockerfile
  #   ports:
  #   - "5432:5432"
  #   volumes:
  #   - ../data/osmcha-db-data:/var/lib/postgresql/data
  #   env_file:
  #   - ../envs/.env.osmcha