apiVersion: batch/v1
kind: Job
metadata:
  name: eoapi-ingest-datasets
spec:
  template:
    spec:
      containers:
      - name: eoapi-ingest-datasets
        image: gcr.io/devseed-labs/eoapi-risk-ingest:{{VERSION}}
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          ./entrypoint.sh
          ### individual datasource ingestions
          # mkdir -p data
          # python entrypoint.py buildings
          # cat data/*.json > data/items.json
          # pypgstac load collections data/collections.json --method insert_ignore
          # pypgstac load items data/items.json --method insert_ignore
        env:
        - name: PGHOST
          value: pgstac
        - name: PGPORT
          value: "5432"
        envFrom:
        - secretRef:
            name: pgstac-secrets-ifrc-eoapi-risk
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data-volume
        emptyDir: {}
  backoffLimit: 0
