apiVersion: batch/v1
kind: Job
metadata:
  name: eoapi-ingest-datasets
spec:
  template:
    spec:
      containers:
      - name: eoapi-ingest-datasets
        image: gcr.io/devseed-labs/eoapi-risk-ingest:0b20a8e
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          export DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@${PGHOST}:${PGPORT}/${POSTGRES_DBNAME}"
          dataOutput=/data
          mkdir -p $dataOutput
          python entrypoint.py population
          python entrypoint.py admin_boundaries
          python entrypoint.py buildings
          python entrypoint.py health_facilities
          python entrypoint.py maxar_opendata
          python entrypoint.py shakemap_peak
        env:
        - name: PGHOST
          value: pgstac
        - name: PGPORT
          value: "5432"
        envFrom:
        - secretRef:
            name: pgstac-secrets-ifrc-eoapi-risk
        volumeMounts:
        - name: data-volume
          mountPath: /data
        resources:
          requests:
            memory: "6Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "1"
      restartPolicy: Never
      volumes:
      - name: data-volume
        emptyDir: {}

  backoffLimit: 0
