apiVersion: batch/v1
kind: Job
metadata:
  name: eoapi-ingest-datasets
spec:
  template:
    spec:
      containers:
      # name should be of the form: eoapi-ingest-<dataset-name>
      - name: eoapi-ingest-datasets
        image: gcr.io/devseed-labs/eoapi-risk-ingest:latest
        imagePullPolicy: Always
        ### commands to run to ingest all datasets, check config.py
        command:
        - sh
        - -c
        - |
          ./entrypoint.sh
        env:
        - name: PGHOST
          value: pgstac
        - name: PGPORT
          value: "5432"
        envFrom:
        - secretRef:
            name: pgstac-secrets-ifrc-eoapi-risk
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data-volume
        emptyDir: {}
  backoffLimit: 0
