db:
  settings:
    secrets:
      PGUSER: "dbuser"
      POSTGRES_USER: "dbuser"
      PGPASSWORD: ""
      POSTGRES_PASSWORD: ""
    resources:
      requests:
        storage: "100Mi"
        cpu: "212m"
        memory: "512Mi"
      limits:
        cpu: "512m"
        memory: "1024Mi"

raster:
  enabled: true
  image:
    name: ghcr.io/stac-utils/titiler-pgstac
    tag: uvicorn-1.2.0
  settings:
    resources:
      requests:
        cpu: "256m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "2048Mi"

vector:
  enabled: true
  image:
    name: ghcr.io/developmentseed/tipg
    tag: uvicorn-0.6.1
  settings:
    envVars:
      TIPG_CATALOG_TTL: "300"
    resources:
      requests:
        cpu: "256m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "2048Mi"

ingress:
  host: eoapi.ifrc-risk.k8s.labs.ds.io
  tls:
    enabled: true
    secretName: eoapi-tls
    certManager: true
    certManagerIssuer: letsencrypt-prod
    cerrtManagerEmail: tarashish@developmentseed.org
