db:
  image:
    name: ghcr.io/stac-utils/pgstac
    tag: v0.8.4
  settings:
    secrets:
      PGUSER: "dbuser"
      POSTGRES_USER: "dbuser"
      PGPASSWORD: ""
      POSTGRES_PASSWORD: ""
    resources:
      requests:
        storage: "100Mi"
        cpu: "1000m"
        memory: "2048Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"

raster:
  enabled: true
  image:
    name: ghcr.io/stac-utils/titiler-pgstac
    tag: uvicorn-1.2.1
  settings:
    envVars:
      TITILER_PGSTAC_API_ROOT_PATH: "/raster"
      AWS_NO_SIGN_REQUEST: "YES"
    resources:
      requests:
        cpu: "500m"
        memory: "1024Mi"
      limits:
        cpu: "1000m"
        memory: "2048Mi"

vector:
  enabled: true
  image:
    name: ghcr.io/developmentseed/tipg
    tag: uvicorn-0.6.2
  settings:
    envVars:
      TIPG_CATALOG_TTL: "300"
      TIPG_ROOT_PATH: "/vector"
    resources:
      requests:
        cpu: "1000m"
        memory: "2048Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"

ingress:
  host: eoapi.ifrc-risk.k8s.labs.ds.io
  tls:
    enabled: true
    secretName: eoapi-tls
    certManager: true
    certManagerIssuer: letsencrypt-prod
    cerrtManagerEmail: tarashish@developmentseed.org
