name: Build Docker image for ingestion jobs and push to GCR

on:
  push:
    branches:
    - '*'
    paths:
    - 'ingest/**'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE: eoapi-risk-ingest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Shorten git SHA
      id: shorten_sha
      run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ingest
        push: true
        tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.ref == 'refs/heads/main' && 'latest' || env.SHORT_SHA }}
